data-apis/dataframe-api

protocol/dataframe_protocol.py
protocol/pandas_implementation.py

This PR supersedes [gh-45](https://github.com/data-apis/dataframe-api/pull/45) in order to ensure a cleaner merge and, similar to [gh-45](https://github.com/data-apis/dataframe-api/pull/45),
-   adds variable-length string support to the dataframe interchange protocol.
-   modifies the protocol to return a dictionary containing all possible data buffers, rather than separate methods for retrieving data, validity, and offsets buffers, as discussed in consortium meetings.
-   modifies the protocol to return both the buffers and their associated dtypes. This is necessary in order to interpret, e.g., the `offsets` and `mask` buffers.
-   updates source code documentation (punctuation, typos, and spelling).
-   manually copies string data to and from byte arrays, as it assumes that strings are …

Add variable-length string support

---

protocol/dataframe_protocol.py
protocol/pandas_implementation.py

Add `allow_copy` flag to interchange protocol

---

protocol/pandas_implementation.py

Current tests focus on `from_dataframe` method. To have a better test coverage, I've written some test cases for `__dataframe__` method. Note that this is a starting point. Added tests are not complete e.g `Buffer` tests are missing.

More tests on the API

---

protocol/purpose_and_scope.md

Capitalization. Unless a *no-highlight*, lowercase "pandas" is intended here.

Typo: Fix Purpose and Scope captialization typo

---

protocol/design_requirements.md

'explicitly supported'* not 'support'

Fix Design Requirements typo

---

protocol/dataframe_protocol.py

Signed-off-by: Vasily Litvinov <vasilij.n.litvinov@intel.com>
This is related to #73

Declare enums explicitly, fix type hints

---

protocol/dataframe_protocol.py

This follows up on https://github.com/data-apis/dataframe-api/pull/35#issuecomment-1179154887

Clarify that chunks in `__dataframe__` are equal-size across columns

---

protocol/dataframe_protocol.py

Thanks for this team's efforts in implementing the dataframe interchange protocol.
While experimenting on an implementation for StaticFrame (https://github.com/InvestmentSystems/static-frame/pull/621), I found one aspect of the ABC and associated types unclear.
The `ColumnBuffers` `TypedDict` defines its elements as pairs of `Buffer` and a dtype, but only types the dtype as `Any`. I assume that the dtype should be provided as the same tuple returned from `Column.dtype`. This PR makes this explicit by defining a `Dtype` type alias and using it for the return value of `Column.dtype` as well as the elements in `ColumnBuffers`.
If my assumption is incorrect, it would be helpful to specify the type of the dtype values returned from `ColumnBuffers`.

Clarify dtype type in `ColumnBuffers`  elements

---

.github/workflows/protocol_docs.yml

CI: deploy interchange protocol docs on each commit to main

---

.gitignore
spec/API_specification/column_object.rst
spec/API_specification/column_selection.md
spec/API_specification/dataframe_api/__init__.py
spec/API_specification/dataframe_api/_types.py
spec/API_specification/dataframe_api/dataframe_object.py
spec/API_specification/dataframe_api/groupby_object.py
spec/API_specification/dataframe_basics.md
spec/API_specification/dataframe_object.rst
spec/API_specification/filter_rows.md
spec/API_specification/groupby_object.rst
spec/API_specification/index.rst
spec/_templates/attribute.rst
spec/_templates/method.rst
spec/_templates/property.rst
spec/conf.py

This does the following:
- Ensure the package in `spec/API_specification/dataframe_api/` is importable
- Ensure all docstrings for objects/methods are rendered in the html docs via `autodoc`
- Add a description for operators supported by the dataframe object (and a few TODOs)
- Adds Sphinx templates for styling the html rendered versions of methods and attributes properly (taken over from the array-api repo)
- Adds some infrastructure for static typing that we may need. So far only the `Scalar` class needed a `TypeVar`, but there should be more to do there.

Render API docstrings in `.py` files as html

---

README.md

Update README with more context and links

---

spec/API_specification/dataframe_api/dataframe_object.py

Updates the `DataFrame.groupby` docstring to clarify that orderdedness of both keys and rows within each group is not guaranteed and is implementation defined.
Additionally, changes keys to be a `Sequence[str]` to be in line with other APIs expecting a sequence of column names.

Update groupby docstring to make orderedness explicitly not guaranteed

---

spec/API_specification/dataframe_api/dataframe_object.py

closes #105 
Doesn't look like there's objections, so I went ahead and opened this

Add rename columns and get column names

---

spec/API_specification/dataframe_api/dataframe_object.py

poison __iter__

---

spec/API_specification/dataframe_api/dataframe_object.py

add dataframe property

---

spec/API_specification/dataframe_api/dataframe_object.py

add an `__invert__` method to `DataFrame`

---

.github/workflows/preview.yml

The added token has to be a personal token; I generated that within the CircleCI app.

Fix the Circle CI preview link on PRs

---

spec/API_specification/dataframe_api/dataframe_object.py
spec/API_specification/dataframe_api/groupby_object.py

Rename skipna => skip_nulls

---

spec/API_specification/dataframe_api/dataframe_object.py

DataFrame.get_rows should take Column, not Sequence

---

spec/API_specification/dataframe_api/dataframe_object.py

as discussed on the latest call

Add from_dict classmethod

---

spec/API_specification/dataframe_api/column_object.py

add Column.from_sequence

---

spec/design_topics/index.rst
spec/design_topics/python_builtin_types.md

This addresses a concern that has come up a number of times about whether it's okay to implement a library-specific object instead of a builtin type. E.g.,
https://github.com/data-apis/dataframe-api/pull/140#discussion_r1171567591

Add design topic page on use of Python builtin types

---

spec/API_specification/dataframe_api/dataframe_object.py

add `DataFrame.sorted_indices`

---

spec/API_specification/dataframe_api/dataframe_object.py
spec/API_specification/index.rst
spec/future_API_evolution.md
spec/purpose_and_scope.md

All this is taken over from the array API standard, where the approach is now stable and the kinks have been worked out.
Closes gh-115
Closes gh-79

Add a way to retrieve the standard-compliant namespace, fill "how to adopt" and "future evolution"

---

spec/API_specification/dataframe_api/__init__.py
spec/API_specification/dataframe_api/column_object.py

closes https://github.com/data-apis/dataframe-api/issues/162

move from_sequence to namespace

---

spec/API_specification/dataframe_api/__init__.py
spec/API_specification/index.rst

Also includes `__dataframe_api_version__`, which was already present, into the API specification.
The table of top-level objects/functions will remain pretty sparse, but there's probably a few more things that need adding. `concat` for one, see gh-137.
I'll note that I briefly considered whether this should be spelled `NULL` or `Null`, but went with `null` because that seemed most natural (e.g., `DataFrame.from_sequence([1, 2, null, np.nan]`).

Add `null` object, and update top-level API specification

---

spec/API_specification/dataframe_api/__init__.py
spec/API_specification/dataframe_api/column_object.py
spec/API_specification/dataframe_api/dataframe_object.py

Addresses half of gh-142 (`fill_null` is more complex, and not included here).
*Note: this is reviewable now, but should be merged after gh-157 which introduces the `null` object).*

Add a `fill_nan` method to dataframe and column

---

spec/API_specification/dataframe_api/dataframe_object.py

there's already namespace.dataframe_from_dict, let's not repeat the same "1000 ways to do the same thing" there is in pandas

remove from_dict

---

spec/API_specification/dataframe_api/__init__.py
spec/API_specification/dataframe_api/column_object.py
spec/API_specification/dataframe_api/dataframe_object.py
spec/API_specification/index.rst

resurrecting #111 as this has been annoying me slightly
it's true that python numpy and pandas are inconsistent here, but we have chance to do things differently and better in this standard - I suggest we just use snake case consistently

use snake case

---

spec/API_specification/dataframe_api/column_object.py
spec/API_specification/dataframe_api/dataframe_object.py

Pretty minor, hope this is uncontroversial
use-case: you have a function which accepts a Column as input, and you need to access some method from the top-level namespace

add `Column.__dataframe_namespace__`

---

protocol/purpose_and_scope.md

update docs on how to opt-in

---

spec/API_specification/dataframe_api/column_object.py

looks like we missed this one when adding DataFrame.sorted_indices

Add column.sorted_indices

---

spec/API_specification/dataframe_api/column_object.py
spec/API_specification/dataframe_api/dataframe_object.py

Note __pow__ return type

---

spec/API_specification/dataframe_api/column_object.py
spec/API_specification/dataframe_api/dataframe_object.py
spec/API_specification/dataframe_api/groupby_object.py

Add a `correction` keyword to the `std` methods

---

spec/API_specification/dataframe_api/column_object.py

I noticed plotly uses some cumulative functions (`Series.cumsum`) - OK to start adding some simple and common cumulative operations to `Column`?

Add some cumulative Column operations

---

spec/API_specification/dataframe_api/column_object.py
spec/API_specification/dataframe_api/dataframe_object.py

Follow-up to gh-167, which added `fill_nan`, and closes gh-142.
As discussed in gh-142, this does only the scalar case now. I think the main thing that could be done differently is `column_names`. This seemed like the most logical thing to do, keeping `value` to a scalar only. It matches what Vaex does. Pandas instead allows value to be: `scalar, dict, Series, or DataFrame`. Polars doesn't seem to have any way of dealing with non-uniform dtypes of columns.

Add a `fill_null` method to dataframe and column

---

spec/API_specification/dataframe_api/column_object.py
spec/API_specification/dataframe_api/dataframe_object.py

analogous to the already-existing Column.unique_indices

Add `DataFrame.unique_indices`

---

spec/API_specification/dataframe_api/dataframe_object.py

a few other methods allow this (`unique_indices`, `fill_null`) so we should probably add it here too

let `keys` be none in sorted_indices

---

spec/API_specification/dataframe_api/column_object.py
spec/API_specification/dataframe_api/dataframe_object.py

Trying to move this forwards, according to my understanding
Sorry if I've misunderstood the
>         While numpy arrays are not yet array-API-compliant, implementations
>        may choose to return a numpy array (for numpy prior to 2.0), with the
>        understanding that consuming libraries would then use the
>        ``array-api-compat`` package to convert it to a Standard-compliant array.
part

Add DataFrame.to_array_object and Column.to_array_object

---

spec/API_specification/dataframe_api/__init__.py
spec/API_specification/index.rst

Also a request from scikit-learn

Add 2d constructor

---

spec/purpose_and_scope.md

Renaming to make this more amenable to pandas

Rename entrypoints to `__dataframe_consortium_standard__` and `__column_consortium_standard__`

---

spec/purpose_and_scope.md

Didn't notice these in the other PR (gh-214).

Address leftover renaming away from `__dataframe_standard__`

---

spec/API_specification/dataframe_api/_types.py
spec/API_specification/dataframe_api/column_object.py
spec/API_specification/dataframe_api/dataframe_object.py
spec/conf.py
spec/design_topics/python_builtin_types.md

Some column methods can return `null` if `skip_nulls` is `False`, but the return annotations don't currently capture that
~edit: wait, `null` isn't a valid type~ have added `NullType` (but just used internally, it's not exported)

Fix up some return types for methods with `skip_nulls`

---

spec/API_specification/dataframe_api/column_object.py
spec/API_specification/dataframe_api/dataframe_object.py

not all dataframe dtypes are supported by the array api (e.g. `datetime`), so just accepting the same ones and sometimes raising `NotImplementedError` may not be the best experience
How about just accepting `str`, and listing the allowed strings? These dtypes don't need to store anything (like categories / time unit / time zone), so don't need to be classes anyway.
Internally, each implementation can map to the correct object (e.g. for pandas: 'int64' would go to np.int64)

to_array_object: type dtype as str, note possibilities

---

spec/API_specification/dataframe_api/__init__.py
spec/API_specification/dataframe_api/column_object.py

Noticed this while updating the polars implementation: their series must have a `str` name, and can't be `None`
We _could_ hack around this in the implemenation, but I think it's easier to just require the name to only be `str`
Afterall:
- if a column is created from a dataframe (e.g. `df.get_column_by_name('foo')`), then its name will be the column name (which has to be `str`)
- if a column is constructed from a sequence or 1d array, then we can require that a `str` `name` be specified
So, `name` will always be `str`

Don't let Column.name be None

---

spec/API_specification/dataframe_api/dataframe_object.py

There's a couple of things I don't like about `DataFrame.insert`:
- the name is less descriptive than the rest of the API
- the argument `label` isn't really needed, because we have both `Column.name` and `Column.rename`

Rename insert, remove label argument

---

spec/API_specification/dataframe_api/column_object.py
spec/API_specification/dataframe_api/dataframe_object.py

Feedback I received when showing this to people is that
```python
col.get_rows(col.sorted_indices())
```
isn't ergonomic
It's also a performance footgun
```python
In [1]: df = pl.DataFrame({'a': np.random.randint(0, 4, size=100_000_000)})
In [2]: %timeit df[df['a'].arg_sort()]
2.56 s ± 80.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
In [3]: %timeit df.sort('a')
700 ms ± 21.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

Add DataFrame.sort and Column.sort

---

spec/API_specification/dataframe_api/dataframe_object.py

remove loc from insert_column

---

spec/API_specification/dataframe_api/dataframe_object.py

Add dataframe.join

---

spec/API_specification/dataframe_api/dataframe_object.py

Updating the values in a column is quite inconvenient currently:
```python
idx = df.get_column_names().index(column_names)
df = df.drop_column(column_name)
df = df.insert_column(idx, new_column)
```
This could be done more simply with
```python
df = df.update_column(new_column)
```

Add DataFrame.update_columns

---

protocol/dataframe_protocol.py

As discussed in #226
This PR adds a warning to the `nan_as_null` parameter.

Add warning for nan_as_null

---

spec/API_specification/dataframe_api/dataframe_object.py

Just out of interest, has any here ever needed to sum two entire dataframes? I haven't, and don't think there's much use for these comparison ops when `other` is a dataframe
It also avoids some of the discussion in #224 - if it can't be done, there's no need to document that in some cases it might not be allowed

Remove cross-dataframe comparisons

---

spec/API_specification/dataframe_api/dataframe_object.py
spec/API_specification/dataframe_api/groupby_object.py

This is what the ecosystem generally does:
- SQL has `GROUP BY`
- pyspark has `groupBy` (note that the `B` is capitalised, as it's the start of a new word)
- dplyr has `group_by`
- polars has `group_by`
- it's two words
I guess the only reason it's currently `groupby` is because that's what pandas did?
But that API is now so far away from pandas anyway, so I suggest we follow the broader ecosystem

Rename groupby to group_by

---

spec/purpose_and_scope.md

the current example shows new syntax but an old api version
going to self-merge as this is super-minor (and people aren't around anyway)

DOCS fix api version

---

spec/API_specification/dataframe_api/dataframe_object.py
spec/purpose_and_scope.md

Similar to #245 and #246, trying to improve ergonomics whilst we're still "beta"
I think we've agreed that although the number of rows (and their ordering) isn't always known, we do always know the number of columns (if we didn't, then `get_column_names` would already be broken), and that this shouldn't really involve any compute

Rename `get_column_names` to `column_names` and make property

---

spec/API_specification/dataframe_api/__init__.py
spec/API_specification/dataframe_api/_types.py
spec/API_specification/dataframe_api/column_object.py
spec/API_specification/dataframe_api/dataframe_object.py
spec/API_specification/dataframe_api/dtypes.py

Summary:
- make `DType` a type alias
- remove several unused TypeVars (we'd agreed to disagree on removing them in https://github.com/data-apis/dataframe-api/pull/198/files, but some still remain)

remove unused typevars, make dtype type alias

---

spec/API_specification/dataframe_api/dataframe_object.py
spec/purpose_and_scope.md

closes #235 
I think I made a mistake in splitting "set_column" into "insert_column" and "update_column":
1. first, because having tried using the Standard to write code a while now, it's really tedious to have to distinguish them
2. because I don't think any existing dataframe library has this distinction
3. a users has brought this up too (#235)
In keeping with the goal of making the standard feel familiar, let's look at what existing dataframe libraries do:
- pandas and its clones: either `__setitem__` (which the consortium doesn't want) or `DataFrame.assign`
- pyspark / polars: `DataFrame.with_columns`
- ibis: `DataFrame.mutate`
- datatable: `update / extend`
I don't really mind which one we go with. I'm suggesting `with_columns` here as I think it's probably the most explicit

update/insert columns -> assign

---

spec/API_specification/dataframe_api/__init__.py

These are unnessary, as the namespace will already have been instantiated to follow a given api version
e.g.
```python
df, xp = df.__dataframe_consortium_standard__(api_version='2023.09-beta')
```

remove some unnecessary api_version args

---

.github/workflows/mypy.yml
spec/API_specification/dataframe_api/__init__.py
spec/API_specification/dataframe_api/_types.py
spec/API_specification/dataframe_api/column_object.py
spec/API_specification/dataframe_api/dataframe_object.py
spec/API_specification/dataframe_api/dtypes.py
spec/API_specification/examples/01_standardise_columns.py
spec/API_specification/examples/02_plotting.py
spec/API_specification/examples/README.md
spec/conf.py
spec/purpose_and_scope.md

needs rebasing onto https://github.com/data-apis/dataframe-api/pull/266
---
It's going to be virtually impossible to keep the example in the docs up-to-date, so I suggest we make a separate `examples` folder, which we can type check in CI and make sure it keeps working

Add examples

---

spec/API_specification/dataframe_api/__init__.py
spec/API_specification/dataframe_api/_types.py
spec/API_specification/dataframe_api/dtypes.py
spec/API_specification/index.rst

I suggest we leave categorical for a separate PR (will probably require discussion)
---
EDIT: marking as draft for now, let's leave this out from the first version

Add some more dtypes: Date, Datetime, Duration, String

---

spec/API_specification/dataframe_api/dataframe_object.py
spec/API_specification/examples/tpch/q5.py
spec/conf.py

needs rebasing onto #282 when that's in

Add TPC-H query 5 to examples

---

spec/API_specification/dataframe_api/typing.py

these were meant to have been removed in https://github.com/data-apis/dataframe-api/pull/264

remove some outdated api_version args

---

spec/API_specification/dataframe_api/dataframe_object.py

I'd like to suggest passing multiple columns positionally, rather than as `str | list[str]`.
First, this is more ergonomic to write, as it saves an extra pair of brackets (and an extra level
of indentation...).
Second, because this is actually already supported in both pandas and Polars:
```python
In [2]: df.assign(
...:     d=lambda x: x['a']*2,
...:     e=lambda x: x['b'] - x['a']
...: )
Out[2]:
a  b  c  d  e
0  1  4  4  2  3
1  2  5  2  4  3
2  3  6  1  6  3
In [1]: df.with_columns(
...:     d=pl.col('a')*2,
...:     e=pl.col('b')-pl.col('a')
...: )
Out[1]:
shape: (3, 5)
┌─────┬─────┬─────┬─────┬─────┐
│ a   ┆ b   ┆ c   ┆ d   ┆ e   │
│ --- ┆ --- ┆ --- ┆ --- ┆ --- │
│ i64 ┆ i64 ┆ i64 ┆ i64 ┆ i64 │
╞═════╪═════╪═════╪═════╪═════╡
│ 1   ┆ 4   ┆ 4   ┆ 2   ┆ 3   │
│ 2   ┆ 5   ┆ 2   ┆ 4   ┆ …
```

Allow for positional arguments instead of str | list[str]

---

.github/workflows/mypy.yml
spec/API_specification/dataframe_api/column_object.py
spec/API_specification/dataframe_api/dataframe_object.py
spec/conf.py

We're not saying that
```python
s1: PandasColumn
s2: FancyColumn
s1 + s2
```
is supported, so let's use `Self`
Else implementations will get
```console
t.py:18: error: Argument 1 of "add" is incompatible with supertype "Cat"; supertype defines the argument type as "Cat"  [override]
t.py:18: note: This violates the Liskov substitution principle
t.py:18: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#incompatible-overrides
t.py:21: error: Argument 1 of "sub" is incompatible with supertype "Cat"; supertype defines the argument type as "Cat"  [override]
t.py:21: note: This violates the Liskov substitution principle
t.py:21: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#incompatible-overrides
Found 2 errors in 1 file (checked 1 source file)
```

use other: Self instead of other: Column

---

spec/API_specification/dataframe_api/__init__.py
spec/API_specification/dataframe_api/_types.py
spec/API_specification/examples/02_plotting.py
spec/API_specification/index.rst

`Column`s have names, so `dataframe_from_dict` isn't really necessary
drive-by: removing `api_version` from the functions in the `Namespace` protocol, which I should've done in https://github.com/data-apis/dataframe-api/pull/264

Replace dataframe_from_dict with dataframe_from_columns

---

spec/API_specification/dataframe_api/column_object.py
spec/API_specification/dataframe_api/dataframe_object.py
spec/API_specification/examples/02_plotting.py

Couple of things here:
- `to_array_object` is quite long. The docstring already describes what exactly the method does. Could it just be `to_array` instead?
- In the Column case, can we remove the `dtype` argument? Much simpler to just convert to the respective dtype, and "force" users to fill nulls before hand

rename to_array_object to to_array, remove `dtype` argument in Column case

---

spec/API_specification/.mypy.ini
spec/API_specification/dataframe_api/__init__.py
spec/API_specification/dataframe_api/column_object.py
spec/API_specification/dataframe_api/dataframe_object.py
spec/API_specification/dataframe_api/groupby_object.py

technically we're defining protocols here - classes which must have certain attributes and methods
might as well type these as Protocol anyway. this will make type checking for implementations simpler, as it tells you whether anything's missing
minimal demo of how this helps:
```console
(.venv) marcogorelli@DESKTOP-U8OKFP3:~/tmp$ cat t.py
from __future__ import annotations
from typing import Protocol
from typing_extensions import Self
class Cat(Protocol):
def add(self, other: Self) -> Self:
...
def sub(self, other: Self) -> Self:
...
class FancyCat(Cat):
def __init__(self, value: int):
self._value = value
def add(self, other: Self) -> FancyCat:
return FancyCat(self._value + other._value)
(.venv) marcogorelli@DESKTOP-U8OKFP3:~/tmp$ mypy t.py
t.py:19: error: Cannot instantiate abstract …
```

type DataFrame, Column, and GroupBy as Protocol

---

spec/API_specification/dataframe_api/typing.py

I'd missed a couple of details in my implementation, the more accurate and usable the typing is the more that can be avoided

Fixup typing of Namespace

---

spec/API_specification/dataframe_api/__init__.py
spec/API_specification/dataframe_api/groupby_object.py
spec/API_specification/dataframe_api/typing.py
spec/API_specification/examples/tpch/q1.py
spec/API_specification/examples/tpch/q5.py
spec/conf.py

closes #274 
the gist of the PR is that it lets you write
```python
result = (
lineitem.filter(mask)
.group_by(["l_returnflag", "l_linestatus"])
.aggregate(
namespace.Aggregation.sum("l_quantity").rename("sum_qty"),
namespace.Aggregation.sum("l_extendedprice").rename("sum_base_price"),
namespace.Aggregation.sum("l_disc_price").rename("sum_disc_price"),
namespace.Aggregation.sum("change").rename("sum_charge"),
namespace.Aggregation.mean("l_quantity").rename("avg_qty"),
namespace.Aggregation.mean("l_discount").rename("avg_disc"),
namespace.Aggregation.size().rename("count_order"),
)
.sort(["l_returnflag", "l_linestatus"])
)
```

Add GroupBy.aggregate (and tpch-1 query to examples)

---

spec/API_specification/dataframe_api/typing.py
spec/API_specification/examples/02_plotting.py
spec/API_specification/examples/tpch/q5.py
spec/purpose_and_scope.md

I think the current policy will lead to breakage: #257 
The current policy, as far as I can tell, kind of implies that we need perfect backwards compatibility. Or to coordinate multi-year changes across multiple projects, which sounds...really hard
I'd suggest just making `api_version` a required argument. This just simplifies everything

make api_version required

---

spec/API_specification/dataframe_api/__init__.py
spec/API_specification/dataframe_api/column_object.py
spec/API_specification/dataframe_api/typing.py

The keys of `dtypes` already give the column names, and Python dicts are ordered
If anyone needs to reorder the names after construction, they can put `.select` after this method anyway
But having to always provide both `dtypes` and `names` is quite annoying from a user perspective

remove `names` from dataframe_from_2d_array

---

spec/API_specification/dataframe_api/typing.py

It's going to be quite annoying to have to keep this class in-sync with the main module - I'd suggest just making a `Namespace` Protocol class in `__init__.py`, but that's for a separate PR

fix typing of dataframe_from_2d_array

---

spec/API_specification/dataframe_api/__init__.py

`DataFrame.insert` has been renamed to `DataFrame.assign`, and isn't really a complete replacement for horizontal concatenation. I'd suggest just removing the sentence for now, we can always add horizontal concatenation if/when the need arises

remove mention of DataFrame.insert from concat docstring

---

spec/API_specification/dataframe_api/column_object.py
spec/API_specification/dataframe_api/dataframe_object.py
spec/design_topics/execution_model.md
spec/design_topics/index.rst
spec/purpose_and_scope.md

For now I'm keeping `Column.to_array` out of it - once we sort out #298 , we can add that too

Add DataFrame.persist, and notes on execution model

---

spec/API_specification/dataframe_api/column_object.py

Noticed in scikit-lego, but really any library related to forecasting would need this

add column.shift

---

spec/API_specification/dataframe_api/column_object.py
spec/API_specification/dataframe_api/dataframe_object.py

I think we can relax many of these restrictions for the case of free-standing columns (i.e. those without a parent dataframe, created via `column_from_1d_array`) - just working through it to check, will update this week

Add note about parent dataframes and cross-dataframe column comparisons

---

protocol/dataframe_protocol.py

As explained by @pitrou in https://github.com/data-apis/dataframe-api/issues/251, this section is just wrong, so I would propose to remove it entirely.
Closes #251

Remove Column docstring section about Arrow's null dtype

---

spec/API_specification/dataframe_api/typing.py

add the `time_unit` and `time_zone` attributes

fixup typing of Duration and Datetime dtypes

---

spec/API_specification/dataframe_api/__init__.py
spec/API_specification/dataframe_api/column_object.py
spec/API_specification/dataframe_api/dataframe_object.py
spec/API_specification/dataframe_api/typing.py
spec/API_specification/examples/06_horizontal_functions.py

The current `any_rowwise` function isn't particularly useful for filtering:
```python
df: DataFrame
df.filter((df > 0).any_rowwise())
```
is undefined, because the parent dataframe of `(df > 0).any_rowwise()` is `df > 0`, not `df`
Solution: introduce `namespace.any_rowwise` and `namespace.all_rowwise`. Also, rename to `_horizontal` for familiarity to Polars users (I'm not aware of other names - in spark I think you're meant to do something like
```python
from functools import reduce
predicate = reduce(lambda a, b: a | b, [df[x] != 0 for x in cols])
```
)
Then, you can write
```python
>>> df: DataFrame
>>> ns = df.__dataframe_namespace__()
>>> mask = ns.all_horizontal(
...     *[df.col(col_name) > 0 for col_name in df.column_names()]
... )
>>> df = df.filter(mask)
```
Maybe, in a separate …

Make DataFrame.any_rowwise top-level, rename to _horizontal

---

spec/API_specification/dataframe_api/__init__.py
spec/API_specification/dataframe_api/groupby_object.py
spec/API_specification/examples/02_plotting.py
spec/API_specification/examples/03_working_with_nulls.py
spec/API_specification/examples/04_datatypes.py
spec/API_specification/examples/06_horizontal_functions.py
spec/API_specification/examples/tpch/q1.py
spec/API_specification/examples/tpch/q5.py

`namespace = dataframe.__dataframe_namespace__()` is quite verbose, how about just using a 2-letter acronym in the examples? most people alias namespace to 2-letter acronyms anyway

Consistently use ns for namespace in docs/examples

---

spec/API_specification/dataframe_api/scalar_object.py

There are already:
- `DataFrame.dataframe`
- `Column.column`
so I think there should also be `Scalar.scalar`
This also solves the problem of how to get the scalar object our of a Scalar if it's not one you can call `__bool__` on (say, to get a Python scalar out of a Duration column)

add Scalar.scalar

---

spec/API_specification/examples/03_sklearn_like_pipeline.py
spec/API_specification/examples/07_sklearn_like_pipeline.py

This is an example of how a (possibly) lazy data frame may be use in a sklearn-like pipeline.
The example is motivated by the prospect of a fully lazy, ONNX-based data frame implementation. The concept is that calls to `fit` are eager. They compute some state that is later meant to be transferred into the ONNX graph/model. That transfer happens when calling `transform`. The logic within the `transform` methods is "traced" lazily and the resulting lazy object is then exported to ONNX.
Related to #281 and https://github.com/data-apis/dataframe-api/pull/249#issuecomment-1769213663

Add example of a sklearn like pipeline

---

spec/API_specification/dataframe_api/dataframe_object.py
spec/API_specification/examples/01_standardise_columns.py
spec/API_specification/examples/04_datatypes.py
spec/design_topics/execution_model.md

This simplifies a few examples and makes things more ergonomic
Can't just use `DataFrame.columns` as pandas / Polars already use that for column names unfortunately

Add DataFrame.iter_columns() and simplify

---

spec/API_specification/dataframe_api/__init__.py
spec/API_specification/dataframe_api/column_object.py
spec/API_specification/dataframe_api/dataframe_object.py

In pandas, there's `.iloc`, but the consortium doesn't want that
Polars has `.gather`
pytorch also uses `gather` for this kind of operation:
```python
>>> t = torch.tensor([1, 2, 3, 4])
>>> torch.gather(t, 0, torch.tensor([3, 2]))
tensor([4, 3])
```
tensorflow has `gather`, which does the same kind of thing https://www.tensorflow.org/api_docs/python/tf/gather
I've not seen `get_rows` anywhere, it's definitely not a common name. Personally I'd rather go with common existing names than create new ones
I promise I'll stop bikeshedding after February (when we aim to make the first non-beta release), trying to get it all out before then

rename get_rows to take

---

spec/API_specification/dataframe_api/dataframe_object.py

In general, most methods which work on columns don't have a `_columns` suffix:
- we have `DataFrame.assign`, not `DataFrame.assign_columns`
- `DataFrame.select`, not `DataFrame.select_columns`
I suggest just having `DataFrame.drop` and `DataFrame.rename` then (it's not like they're ambiguous - we don't have row labels in the standard, so it's not like they can refer to row labels...)

rename: drop_columns -> drop, rename_columns -> rename

---

spec/API_specification/dataframe_api/scalar_object.py

similar to Column.parent_dataframe

Add Scalar.parent_dataframe
